export { default as NavBar } from './NavBar/NavBar';
export { default as Card } from './Card/Card';
export { default as Contact } from './Buttons/Contact/Contact';
export { default as ServicesTitle } from './Titles/Services/ServicesTitle';
export { default as UsTitle } from './Titles/Us/UsTitle';
export { default as Budget } from './Buttons/Budget/Budget';
export { default as People } from './People/People';
export { default as Budget1 } from './Budget/Budget1';
export { default as Budget2 } from './Budget/Budget2';
