export { default as NavBar } from './NavBar/NavBar';
export { default as Card } from './Card/Card';
export { default as Contact } from './Buttons/Contact/Contact';
export { default as ServicesTitle } from './Titles/Services/ServicesTitle';
export { default as UsTitle } from './Titles/Us/UsTitle';
export { default as Budget } from './Buttons/Budget/Budget';
export { default as People } from './People/People';
export { default as BudgetTop } from './Budget/BudgetTop';
export { default as BudgetBottom } from './Budget/BudgetBottom';
